### ISSUE TITLE
unstable_flushDiscreteUpdates errors when in StrictMode (React 16.13.1) (SVG core/react 4.0.0)

### ISSUE THREAD

**Issue by deluca-mike** [kmkzt/svg-drawing#273]
The following code causes many direct ui flush warnings/errors in React when moving the slider, only when the svg-drawing object is rendered.

```jsx
import React, { Fragment, useCallback, useState } from 'react';
import { useSvgDrawing } from '@svg-drawing/react';
import { Slider } from '@material-ui/core';
import Typography from '@material-ui/core/Typography';

function App() {
  const [radius, setRadius] = useState(10);
  const [renderRef, draw] = useSvgDrawing();

  const handleChangeRadius = useCallback((_, value) => {
    const num = Number(value);

    if (Number.isNaN(num)) return;

    draw.changePenWidth(num);
    setRadius(num);
  }, [draw]);

  return (
    <Fragment>
      <div ref={renderRef}/>

      <div>
        <Typography variant="body2" color="secondary">Radius</Typography>
        <Slider value={radius} valueLabelDisplay="auto" step={1} min={1} max={40} onChange={handleChangeRadius}/>
      </div>
    </Fragment>
  )
}

export default App;
```

React error: `Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering.`

**Comment by kmkzt** [comment]
Thank you for reporting any issues.

I have a [similar implementation](https://github.com/kmkzt/svg-drawing/blob/master/examples/docs/pages/demo/drawing.tsx#L107-L115
) on the demo page, but I can't reproduce it.

I think the problem is the combination with other libraries. Is there a repository that you are reproducing?

**Comment by kmkzt** [comment]
@deluca-mike 

I tried adding strict mode to the demo page, but it couldn't be reproduced.

https://github.com/kmkzt/svg-drawing/commit/cca89bb88ec761b9fafa8df914935fe1d9046c61

Maybe it's because you haven't specified the size of the element in the area displaying the SVG.

SVG is now re-rendered to fit the size of the element.
